---
hardening_sysctl:
## Not Exists on RHEL 7
# - { name: kernel.exec-shield, value: 1 } 
- { name: kernel.randomize_va_space, value: 2 }
- { name: net.ipv4.ip_forward, value: 0 }
- { name: net.ipv4.conf.default.rp_filter, value: 1 }
- { name: net.ipv4.conf.default.accept_source_route, value: 0 }
- { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
- { name: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
- { name: kernel.sysrq, value: 0 }
- { name: net.ipv4.tcp_syncookies, value: 1 }
- { name: kernel.msgmnb, value: 65536 }
- { name: kernel.msgmax, value: 65536 }
- { name: kernel.shmmax, value: 68719476736 }
- { name: kernel.shmall, value: 4294967296 }
- { name: kernel.sem, value: 250 1024000 32 4096 }
- { name: kernel.msgmni, value: 16384 }
- { name: net.ipv4.conf.all.log_martians, value: 1 }
- { name: vm.swappiness, value: 0 }
- { name: net.core.somaxconn, value: 50000 }
- { name: net.ipv4.tcp_max_syn_backlog, value: 30000 }
- { name: net.core.netdev_max_backlog, value: 20000 }
- { name: fs.file-max, value: 1500000 }
- { name: net.ipv4.ip_local_port_range, value: 10000 85000 }
- { name: net.ipv4.udp_rmem_min, value: 8192 }
- { name: net.ipv4.udp_wmem_min, value: 8192 }
- { name: net.ipv4.conf.all.send_redirects, value: 0 }
- { name: net.ipv4.conf.all.accept_redirects, value: 0 }
- { name: net.ipv6.conf.all.forwarding, value: 0 }
- { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
- { name: net.ipv4.tcp_window_scaling, value: 1 }
- { name: net.ipv4.tcp_timestamps, value: 1 }
- { name: net.ipv4.tcp_sack, value: 1 }
- { name: net.ipv4.tcp_congestion_control, value: htcp }
- { name: net.ipv4.tcp_keepalive_time, value: 60 }
# - { name: net.netfilter.nf_conntrack_tcp_timeout_time_wait, value: 10 }
# - { name: net.netfilter.nf_conntrack_tcp_timeout_established, value: 300 }
# - { name: net.netfilter.nf_conntrack_generic_timeout, value: 300 }
- { name: net.ipv4.tcp_max_tw_buckets, value: 2000000 }
- { name: net.ipv4.tcp_fin_timeout, value: 10 }
- { name: net.ipv4.tcp_tw_reuse, value: 1 }
- { name: net.ipv4.tcp_keepalive_intvl, value: 15 }
- { name: net.ipv4.tcp_keepalive_probes, value: 5 }
- { name: vm.overcommit_memory, value: 0 }
- { name: net.ipv4.conf.default.send_redirects, value: 0 }
- { name: net.ipv4.conf.all.accept_source_route, value: 0 }
- { name: net.ipv4.conf.default.accept_redirects, value: 0 }
- { name: net.ipv4.conf.all.secure_redirects, value: 0 }
- { name: net.ipv4.conf.default.secure_redirects, value: 0 }
# - { name: net.ipv6.conf.all.accept_ra, value: 0 }
# - { name: net.ipv6.conf.default.accept_ra, value: 0 }
# - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
# - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
# - { name: net.ipv6.conf.all.disable_ipv6, value: 1 }
# - { name: net.ipv6.conf.default.disable_ipv6, value: 1 }
# - { name: net.ipv6.conf.lo.disable_ipv6, value: 1 }
- { name: net.ipv4.conf.all.rp_filter, value: 1 }
# TUNED
- { name: net.core.busy_read, value: 50 }
- { name: net.core.busy_poll, value: 50 }
- { name: net.ipv4.tcp_fastopen, value: 3 }
- { name: kernel.numa_balancing, value: 0 } 

- { name: net.ipv4.tcp_rmem, value: 4096 87380 16777216 }
- { name: net.ipv4.tcp_wmem, value: 4096 16384 16777216 }
- { name: net.ipv4.udp_mem, value: 3145728 4194304 16777216 }

- { name: kernel.hung_task_timeout_secs, value: 600 }
- { name: kernel.nmi_watchdog, value: 0 }
- { name: kernel.sched_rt_runtime_us, value: -1 }
- { name: vm.stat_interval, value: 10 }
- { name: kernel.timer_migration, value: 0 }

remove_sysctl:
- { name: kernel.exec-shield }
- { name: kernel.exec.shield }
- { name: net.bridge.bridge-nf-call-ip6tables }
- { name: net.bridge.bridge-nf-call-iptables }
- { name: net.bridge.bridge-nf-call-arptables }
- { name: net.netfilter.nf_conntrack_tcp_timeout_time_wait }
- { name: net.netfilter.nf_conntrack_tcp_timeout_established }
- { name: net.netfilter.nf_conntrack_generic_timeout }

chipper_start: '# Ansible Chipper start #'
chipper_end: '# Ansible Chipper end #'