---
- name: restart ssh
  service:
    name: "sshd"
    state: restarted

- name: reload sysctl.conf
  command: /sbin/sysctl -p

- name: flush routes
  command: /sbin/sysctl -w net.ipv4.route.flush=1